language: generic
sudo: required
services:
  - docker

before_install:
  - docker build-t yokada0807/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yokada0807/docker-react npm test -- --coverage